### ISSUE TITLE
Model passed a lot around in deserialization

### ISSUE THREAD

**Issue by rand0musername** [PressCentarRacun/smart-wars#19]
I just skimmed but ctrl+clicking down into oblivion I got to NetworkObject:deserializeFrom which takes a model but doesn't use it. Maybe we used to need this but not anymore?

**Comment by geomaster** [comment]
It's for consistency, because all Message types override NetworkObject's deserializeFrom, and some of them do need a model to deserialize themselves (lookup UUIDs, etc.).
